[workspace]
channels = ["conda-forge", "pytorch", "nvidia", "anaconda", "nodefaults"]
name = "acezero"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
ext = "cd dsacstar && python setup.py install"


[dependencies]
_libgcc_mutex = { version = "==0.1", build = "main" }
_openmp_mutex = { version = "==5.1", build = "1_gnu" }
alsa-lib = { version = "==1.2.3.2", build = "h166bdaf_0" }
appdirs = { version = "==1.4.4", build = "pyhd3eb1b0_0" }
blas = { version = "==1.0", build = "mkl" }
blosc = { version = "==1.21.3", build = "h6a678d5_0" }
brotli = { version = "==1.0.9", build = "h5eee18b_7" }
brotli-bin = { version = "==1.0.9", build = "h5eee18b_7" }
brotlipy = { version = "==0.7.0", build = "py38h27cfd23_1003" }
brunsli = { version = "==0.1", build = "h2531618_0" }
bzip2 = { version = "==1.0.8", build = "h7b6447c_0" }
c-ares = { version = "==1.19.0", build = "h5eee18b_0" }
ca-certificates = { version = "==2024.7.2", build = "h06a4308_0" }
cairo = { version = "==1.16.0", build = "h6cf1ce9_1008" }
certifi = { version = "==2024.7.4", build = "py38h06a4308_0" }
cffi = { version = "==1.15.1", build = "py38h5eee18b_3" }
cfitsio = { version = "==3.470", build = "h5893167_7" }
charls = { version = "==2.2.0", build = "h2531618_0" }
charset-normalizer = { version = "==2.0.4", build = "pyhd3eb1b0_0" }
cloudpickle = { version = "==2.0.0", build = "pyhd3eb1b0_0" }
contourpy = { version = "==1.0.5", build = "py38hdb19cb5_0" }
cryptography = { version = "==39.0.1", build = "py38h9ce1e76_0" }
cuda-cudart = { version = "==11.8.89", build = "0" }
cuda-cupti = { version = "==11.8.87", build = "0" }
cuda-libraries = { version = "==11.8.0", build = "0" }
cuda-nvrtc = { version = "==11.8.89", build = "0" }
cuda-nvtx = { version = "==11.8.86", build = "0" }
cuda-runtime = { version = "==11.8.0", build = "0" }
cycler = { version = "==0.11.0", build = "pyhd8ed1ab_0" }
cytoolz = { version = "==0.12.0", build = "py38h5eee18b_0" }
dask-core = { version = "==2022.7.0", build = "py38h06a4308_0" }
dataclasses = { version = "==0.8", build = "pyhc8e2a94_3" }
dbus = { version = "==1.13.6", build = "h48d8840_2" }
expat = { version = "==2.4.8", build = "h27087fc_0" }
ffmpeg = { version = "==4.3.2", build = "hca11adc_0" }
filelock = { version = "==3.9.0", build = "py38h06a4308_0" }
flit-core = { version = "==3.8.0", build = "py38h06a4308_0" }
fontconfig = { version = "==2.14.0", build = "h8e229c2_0" }
fonttools = { version = "==4.25.0", build = "pyhd3eb1b0_0" }
freetype = { version = "==2.12.1", build = "h4a9f257_0" }
freetype-py = { version = "==2.3.0", build = "pyhd8ed1ab_0" }
fsspec = { version = "==2023.3.0", build = "py38h06a4308_0" }
future = { version = "==0.18.3", build = "pyhd8ed1ab_0" }
gettext = { version = "==0.19.8.1", build = "h73d1719_1008" }
giflib = { version = "==5.2.1", build = "h5eee18b_3" }
glib = { version = "==2.68.4", build = "h9c3ff4c_1" }
glib-tools = { version = "==2.68.4", build = "h9c3ff4c_1" }
gmp = { version = "==6.2.1", build = "h295c915_3" }
gmpy2 = { version = "==2.1.2", build = "py38heeb90bb_0" }
gnutls = { version = "==3.6.15", build = "he1e5248_0" }
graphite2 = { version = "==1.3.13", build = "h58526e2_1001" }
gst-plugins-base = { version = "==1.18.5", build = "hf529b03_0" }
gstreamer = { version = "==1.18.5", build = "h76c114f_0" }
harfbuzz = { version = "==2.9.1", build = "h83ec7ef_1" }
hdf5 = { version = "==1.10.6", build = "nompi_h6a2412b_1114" }
icu = { version = "==68.2", build = "h9c3ff4c_0" }
idna = { version = "==3.4", build = "py38h06a4308_0" }
imagecodecs-lite = { version = "==2019.12.3", build = "py38h71d37f0_5" }
imageio = { version = "==2.26.0", build = "py38h06a4308_0" }
importlib_resources = { version = "==5.12.0", build = "pyhd8ed1ab_0" }
intel-openmp = { version = "==2021.4.0", build = "h06a4308_3561" }
jasper = { version = "==1.900.1", build = "h07fcdf6_1006" }
jinja2 = { version = "==3.1.2", build = "py38h06a4308_0" }
joblib = { version = "==1.1.1", build = "py38h06a4308_0" }
jpeg = { version = "==9e", build = "h5eee18b_1" }
jxrlib = { version = "==1.1", build = "h7b6447c_2" }
kiwisolver = { version = "==1.4.4", build = "py38h6a678d5_0" }
krb5 = { version = "==1.19.4", build = "h568e23c_0" }
lame = { version = "==3.100", build = "h7b6447c_0" }
lcms2 = { version = "==2.12", build = "h3be6417_0" }
ld_impl_linux-64 = { version = "==2.38", build = "h1181459_1" }
lerc = { version = "==3.0", build = "h295c915_0" }
libaec = { version = "==1.0.4", build = "he6710b0_1" }
libblas = { version = "==3.9.0", build = "12_linux64_mkl" }
libbrotlicommon = { version = "==1.0.9", build = "h5eee18b_7" }
libbrotlidec = { version = "==1.0.9", build = "h5eee18b_7" }
libbrotlienc = { version = "==1.0.9", build = "h5eee18b_7" }
libcblas = { version = "==3.9.0", build = "12_linux64_mkl" }
libclang = { version = "==11.1.0", build = "default_ha53f305_1" }
libcublas = { version = "==11.11.3.6", build = "0" }
libcufft = { version = "==10.9.0.58", build = "0" }
libcufile = { version = "==1.6.0.25", build = "0" }
libcurand = { version = "==10.3.2.56", build = "0" }
libcurl = { version = "==7.88.1", build = "h91b91d3_0" }
libcusolver = { version = "==11.4.1.48", build = "0" }
libcusparse = { version = "==11.7.5.86", build = "0" }
libdeflate = { version = "==1.17", build = "h5eee18b_0" }
libedit = { version = "==3.1.20221030", build = "h5eee18b_0" }
libev = { version = "==4.33", build = "h7f8727e_1" }
libevent = { version = "==2.1.10", build = "h9b69904_4" }
libffi = { version = "==3.4.2", build = "h6a678d5_6" }
libgcc-ng = { version = "==11.2.0", build = "h1234567_1" }
libgfortran-ng = { version = "==11.2.0", build = "h00389a5_1" }
libgfortran5 = { version = "==11.2.0", build = "h1234567_1" }
libglib = { version = "==2.68.4", build = "h174f98d_1" }
libglu = { version = "==9.0.0", build = "hf484d3e_1" }
libgomp = { version = "==11.2.0", build = "h1234567_1" }
libiconv = { version = "==1.16", build = "h7f8727e_2" }
libidn2 = { version = "==2.3.2", build = "h7f8727e_0" }
liblapack = { version = "==3.9.0", build = "12_linux64_mkl" }
liblapacke = { version = "==3.9.0", build = "12_linux64_mkl" }
libllvm11 = { version = "==11.1.0", build = "hf817b99_2" }
libnghttp2 = { version = "==1.46.0", build = "hce63b2e_0" }
libnpp = { version = "==11.8.0.86", build = "0" }
libnvjpeg = { version = "==11.9.0.86", build = "0" }
libogg = { version = "==1.3.4", build = "h7f98852_1" }
libopencv = { version = "==4.4.0", build = "py38_2" }
libopus = { version = "==1.3.1", build = "h7f98852_1" }
libpng = { version = "==1.6.39", build = "h5eee18b_0" }
libpq = { version = "==13.3", build = "hd57d9b9_0" }
libssh2 = { version = "==1.10.0", build = "h8f2d780_0" }
libstdcxx-ng = { version = "==11.2.0", build = "h1234567_1" }
libtasn1 = { version = "==4.16.0", build = "h27cfd23_0" }
libtiff = { version = "==4.2.0", build = "hf544144_3" }
libunistring = { version = "==0.9.10", build = "h27cfd23_0" }
libuuid = { version = "==2.32.1", build = "h7f98852_1000" }
libvorbis = { version = "==1.3.7", build = "h9c3ff4c_0" }
libwebp = { version = "==1.2.4", build = "h11a3e52_1" }
libwebp-base = { version = "==1.2.4", build = "h5eee18b_1" }
libxcb = { version = "==1.13", build = "h7f98852_1004" }
libxkbcommon = { version = "==1.0.3", build = "he3ba5ed_0" }
libxml2 = { version = "==2.9.12", build = "h72842e0_0" }
libzopfli = { version = "==1.0.3", build = "he6710b0_0" }
locket = { version = "==1.0.0", build = "py38h06a4308_0" }
lz4-c = { version = "==1.9.4", build = "h6a678d5_0" }
markupsafe = { version = "==2.1.1", build = "py38h7f8727e_0" }
matplotlib = { version = "==3.7.1", build = "py38h578d9bd_0" }
matplotlib-base = { version = "==3.7.1", build = "py38h417a72b_1" }
mkl = { version = "==2021.4.0", build = "h06a4308_640" }
mkl-service = { version = "==2.4.0", build = "py38h7f8727e_0" }
mkl_fft = { version = "==1.3.1", build = "py38hd3c417c_0" }
mkl_random = { version = "==1.2.2", build = "py38h51133e4_0" }
mpc = { version = "==1.1.0", build = "h10f8cd9_1" }
mpfr = { version = "==4.0.2", build = "hb69a4c5_1" }
mpmath = { version = "==1.2.1", build = "py38h06a4308_0" }
munkres = { version = "==1.1.4", build = "pyh9f0ad1d_0" }
mysql-common = { version = "==8.0.25", build = "ha770c72_2" }
mysql-libs = { version = "==8.0.25", build = "hfa10184_2" }
ncurses = { version = "==6.4", build = "h6a678d5_0" }
nettle = { version = "==3.7.3", build = "hbbd107a_1" }
networkx = { version = "==2.8.4", build = "py38h06a4308_1" }
nspr = { version = "==4.32", build = "h9c3ff4c_1" }
nss = { version = "==3.69", build = "hb5efdd6_1" }
numpy = { version = "==1.23.5", build = "py38h14f4228_0" }
numpy-base = { version = "==1.23.5", build = "py38h31eccc5_0" }
opencv = { version = "==4.4.0", build = "py38_2" }
openh264 = { version = "==2.1.1", build = "h4ff587b_0" }
openjpeg = { version = "==2.4.0", build = "h3ad879b_0" }
openssl = { version = "==1.1.1w", build = "h7f8727e_0" }
packaging = { version = "==23.0", build = "py38h06a4308_0" }
partd = { version = "==1.2.0", build = "pyhd3eb1b0_1" }
pcre = { version = "==8.45", build = "h9c3ff4c_0" }
pillow = { version = "==9.4.0", build = "py38h6a678d5_0" }
pip = { version = "==23.0.1", build = "py38h06a4308_0" }
pixman = { version = "==0.40.0", build = "h36c2ea0_0" }
pooch = { version = "==1.4.0", build = "pyhd3eb1b0_0" }
pthread-stubs = { version = "==0.4", build = "h36c2ea0_1001" }
py-opencv = { version = "==4.4.0", build = "py38h23f93f0_2" }
pycparser = { version = "==2.21", build = "pyhd3eb1b0_0" }
pyglet = { version = "==1.5.27", build = "py38h578d9bd_3" }
pyopengl = { version = "==3.1.6", build = "pyhd8ed1ab_1" }
pyopenssl = { version = "==23.0.0", build = "py38h06a4308_0" }
pyparsing = { version = "==3.0.9", build = "pyhd8ed1ab_0" }
pyqt = { version = "==5.12.3", build = "py38ha8c2ead_4" }
pyrender = { version = "==0.1.45", build = "pyh8a188c0_3" }
pysocks = { version = "==1.7.1", build = "py38h06a4308_0" }
python = { version = "==3.8.16", build = "h7a1cb2a_3" }
python-dateutil = { version = "==2.8.2", build = "pyhd8ed1ab_0" }
python_abi = { version = "==3.8", build = "2_cp38" }
pytorch = { version = "==2.0.0", build = "py3.8_cuda11.8_cudnn8.7.0_0" }
pytorch-cuda = { version = "==11.8", build = "h7e8668a_3" }
pytorch-mutex = { version = "==1.0", build = "cuda" }
pywavelets = { version = "==1.4.1", build = "py38h5eee18b_0" }
pyyaml = { version = "==6.0", build = "py38h5eee18b_1" }
qt = { version = "==5.12.9", build = "hda022c4_4" }
readline = { version = "==8.2", build = "h5eee18b_0" }
requests = { version = "==2.28.1", build = "py38h06a4308_1" }
scikit-image = { version = "==0.19.3", build = "py38h6a678d5_1" }
scipy = { version = "==1.10.0", build = "py38h14f4228_1" }
setuptools = { version = "==65.6.3", build = "py38h06a4308_0" }
six = { version = "==1.16.0", build = "pyhd3eb1b0_1" }
snappy = { version = "==1.1.9", build = "h295c915_0" }
sqlite = { version = "==3.41.1", build = "h5eee18b_0" }
sympy = { version = "==1.11.1", build = "py38h06a4308_0" }
tifffile = { version = "==2020.6.3", build = "py_0" }
tk = { version = "==8.6.12", build = "h1ccaba5_0" }
toolz = { version = "==0.12.0", build = "py38h06a4308_0" }
torchaudio = { version = "==2.0.0", build = "py38_cu118" }
torchtriton = { version = "==2.0.0", build = "py38" }
torchvision = { version = "==0.15.0", build = "py38_cu118" }
tornado = { version = "==6.1", build = "py38h0a891b7_3" }
trimesh = { version = "==3.21.2", build = "pyhd8ed1ab_0" }
typing_extensions = { version = "==4.4.0", build = "py38h06a4308_0" }
urllib3 = { version = "==1.26.14", build = "py38h06a4308_0" }
wheel = { version = "==0.38.4", build = "py38h06a4308_0" }
x264 = { version = "==1!161.3030", build = "h7f98852_1" }
xorg-kbproto = { version = "==1.0.7", build = "h7f98852_1002" }
xorg-libice = { version = "==1.0.10", build = "h7f98852_0" }
xorg-libsm = { version = "==1.2.3", build = "hd9c2040_1000" }
xorg-libx11 = { version = "==1.7.2", build = "h7f98852_0" }
xorg-libxau = { version = "==1.0.9", build = "h7f98852_0" }
xorg-libxdmcp = { version = "==1.1.3", build = "h7f98852_0" }
xorg-libxext = { version = "==1.3.4", build = "h7f98852_1" }
xorg-libxrender = { version = "==0.9.10", build = "h7f98852_1003" }
xorg-renderproto = { version = "==0.11.1", build = "h7f98852_1002" }
xorg-xextproto = { version = "==7.3.0", build = "h7f98852_1002" }
xorg-xproto = { version = "==7.0.31", build = "h7f98852_1007" }
xz = { version = "==5.2.10", build = "h5eee18b_1" }
yaml = { version = "==0.2.5", build = "h7b6447c_0" }
zfp = { version = "==0.5.5", build = "h295c915_6" }
zipp = { version = "==3.15.0", build = "pyhd8ed1ab_0" }
zlib = { version = "==1.2.13", build = "h5eee18b_0" }
zstd = { version = "==1.5.2", build = "ha4553b6_0" }

[pypi-dependencies]
pyqt5-sip = "==5.12.3"
pyqtchart = "==5.12.3"
pyqtwebengine = "==5.12.3"
roma = "==1.4.1"
timm = "==0.6.7"
pycolmap = "==0.4.0"
